apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    tier: app
    project: roboshop
spec:
  selector:
  # you should provide pod labels here
    app: catalogue
    tier: app
    project: roboshop
  ports:
  - name: catalogue-port
    protocol: TCP
    # service port
    port: 8080
    # pod port
    targetPort: 8080