apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: user
        tier: app
        project: roboshop
    spec:
      containers:
      - name: user
        imagePullPolicy: Always
        image: 338121/user:v1